### PR TITLE
encoding, header, signature

### PR DESCRIPTION
**Pull request by noahhai**
* json or forms encoding
* add custom header (basic auth, etc)
* GitHub-style signature

### CODE REVIEW

**Comment by pydanny** [comment]
Do you want me to release a new version?

**Comment by noahhai** [comment]
Sure! I updated the readme and am using the project in some prod code so
hopefully it's fairly stable.

**Comment by pydanny** [comment]
When I added Python 3.6, tests failed. I'll see what I can do, but as I've grown unfamiliar with the code, my pace will be slow. 😢

**Comment by noahhai** [comment]
ah ok..i can also test that later and fix if you dont get to it

**Pull request merged**
