### PR TITLE
NH - Added encoding and timeout param support and tests with local se…

### PR DESCRIPTION
**Pull request by noahhai**
Added encoding/timeout support and tests.

### CODE REVIEW

**Comment by pydanny** [comment]
Looks like the travis build is non-functional. Can you fix that or would you need my help?

**Comment by noahhai** [comment]
will fix

**Comment by noahhai** [comment]
Fixed the tests!

**Comment by pydanny** [comment]
Did you not want me to merge this in? Or world you like commit rights?

**Comment by noahhai** [comment]
Hey I was using it for an implementation today and had to fix some issues with the changes I had made before. It should be pretty good now, going to do a new PR from another branch. But also might add a few more tests just to be sure.

**Comment by pydanny** [comment]
Would you like commit rights?

**Pull request closed without merging**
